import localFont from 'next/font/local'
import './globals.css'

const poppins = localFont({
	src: './fonts/Poppins.ttf',
	variable: '--font-popa',
	weight: '500',
})
const inter = localFont({
	src: './fonts/Inter.ttf',
	variable: '--font-inter',
	weight: '500',
})

export const metadata = {
	title: 'ТАИЛВИНД ЗДЕСБ',
	description: 'Generated by create next app',
	google:"notranslate"
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${poppins.variable} ${inter.variable} antialiased`}>
				{children}
			</body>
		</html>
	)
}
